USE DEMO

SELECT * FROM WALMART

--REVENU
ALTER TABLE WALMART 
ADD revenue DECIMAL(10,2);
UPDATE WALMART
SET revenue = quantity * unit_price;

--ANALYSIS
--TOTAL SALES REVENUE
SELECT SUM(REVENUE) AS total_revenue FROM WALMART;

--MONTLY SALES TREND
SELECT YEAR(DATE) AS Year, MONTH(DATE) AS Month, SUM(revenue) AS Monthly_Revenue
FROM Walmart
GROUP BY YEAR(DATE), MONTH(DATE)
ORDER BY Year, Month;

--TOP SELLING PRODUCT CATEGORY
SELECT TOP 10 INVOICE_ID, CATEGORY, SUM(Quantity) AS Total_Sold
FROM Walmart
GROUP BY INVOICE_ID, CATEGORY
ORDER BY Total_Sold DESC

--RATING GREATER THAN 8 BASED UPON CATEGORY
SELECT TOP 5 INVOICE_ID,CATEGORY,RATING 
FROM WALMART 
WHERE RATING > 8

--HIGHEST QUANTITY SOLD IN PARICULAR MONTH
SELECT TOP 7 MONTH(DATE) AS Month, INVOICE_ID, CATEGORY, QUANTITY
FROM Walmart
WHERE QUANTITY > 8 

--MOST PROFITABLE PRODUCT
SELECT TOP 5 CATEGORY, SUM(Revenue - UNIT_PRICE) AS Profit
FROM Walmart
GROUP BY CATEGORY
ORDER BY Profit DESC

SELECT * FROM WALMART










